import asyncio
import json
import logging
from collections.abc import Coroutine
from typing import Any, List, TypeVar

from pydantic import BaseModel, ValidationError

from .distributions import Constraints, Correlations
from .llm import get_client
from .llm_driven_analyser import LLMDrivenModelAnalyser
from .prompts import load_prompt
from .sampler import DistributionSampler

logger = logging.getLogger("gendantic")

_T = TypeVar("_T")

# Maximum number of top-up rounds when regenerating records that failed
# validation, before giving up and raising. Each round regenerates only the
# current shortfall, so a non-systematic failure rate converges geometrically
# and this cap is only reached when a validator rejects records persistently.
_MAX_TOPUP_ROUNDS = 10

# A single reusable event loop backs the synchronous wrappers. Using one
# persistent loop (instead of ``asyncio.run``, which creates and tears down a
# fresh loop per call) keeps litellm's cached async HTTP clients bound to a
# live loop, so repeated ``*_sync`` calls in one process don't raise
# "bound to a different event loop".
_sync_loop: asyncio.AbstractEventLoop | None = None


def _run_coro(coro: Coroutine[Any, Any, _T]) -> _T:
    """Run an async coroutine from synchronous code.

    Raises a clear error if called from within an already-running event loop
    (e.g. a Jupyter cell), where the caller should await the async API instead.
    """
    try:
        asyncio.get_running_loop()
    except RuntimeError:
        pass  # no running loop - safe to drive one ourselves
    else:
        coro.close()
        raise RuntimeError(
            "A synchronous gendantic function was called from inside a running "
            "event loop. Use the async API instead (e.g. "
            "`await generate_synthetic_data(...)`)."
        )

    global _sync_loop
    if _sync_loop is None or _sync_loop.is_closed():
        _sync_loop = asyncio.new_event_loop()
    return _sync_loop.run_until_complete(coro)


async def generate_synthetic_data(
    model_class: type[BaseModel],
    count: int = 10,
    *,
    context: str = "general",
    seed: int | None = None,
) -> list[BaseModel]:
    """
    Generate synthetic data records for a Pydantic model.

    Uses numpy sampling for fields with distribution specifications (via Annotated types)
    to guarantee statistical compliance. Remaining fields are generated by the LLM with
    the sampled values as context for coherence.

    Args:
        model_class: The Pydantic model class to generate data for
        count: Number of records to generate
        context: Optional context about the intended use case for better generation
        seed: Random seed for reproducible sampling of distribution fields

    Returns:
        List of model instances with synthetic data

    Examples:
        # Basic generation
        users = await generate_synthetic_data(User, count=100)

        # Context-aware generation
        employees = await generate_synthetic_data(
            Employee,
            count=50,
            context="UK tech startup with remote-first culture"
        )

        # With distribution specifications
        from typing import Annotated
        from gendantic import Normal, Categorical

        class Employee(BaseModel):
            salary: Annotated[int, Normal(mean=50000, std=15000)]
            department: Annotated[str, Categorical(weights={"Eng": 0.6, "Sales": 0.4})]
            name: str  # Generated by LLM

        # salary and department sampled by numpy, name generated by LLM
        employees = await generate_synthetic_data(Employee, count=100, seed=42)
    """

    if context == "general":
        context = f"Modern business using {model_class.__name__} data model"
    return await _generate_with_distribution_sampling(model_class, count, context, seed)


async def generate_synthetic_data_batch(
    model_class: type[BaseModel],
    contexts: List[str],
    count: int = 10,
    *,
    seed: int | None = None,
) -> List[list[BaseModel]]:
    """
    Generate multiple batches of synthetic data with different contexts concurrently.

    Args:
        model_class: The Pydantic model class to generate data for
        contexts: List of contexts for different batches
        count: Number of records per batch
        seed: Random seed for reproducible sampling of distribution fields

    Returns:
        List of lists, each containing model instances for one context

    Examples:
        contexts = ["UK bank", "US startup", "German manufacturing"]
        batches = await generate_synthetic_data_batch(Employee, contexts, count=20)
    """

    tasks = [
        generate_synthetic_data(model_class, count, context=context, seed=seed)
        for context in contexts
    ]
    return await asyncio.gather(*tasks)


def generate_synthetic_data_sync(
    model_class: type[BaseModel],
    count: int = 10,
    *,
    context: str = "general",
    seed: int | None = None,
) -> list[BaseModel]:
    """Synchronous wrapper around :func:`generate_synthetic_data`.

    Convenient for scripts and REPL use where you don't want to manage an event
    loop. Must not be called from within a running event loop (await the async
    version there instead).

    Examples:
        employees = generate_synthetic_data_sync(Employee, count=100, seed=42)
    """
    return _run_coro(
        generate_synthetic_data(model_class, count, context=context, seed=seed)
    )


def generate_synthetic_data_batch_sync(
    model_class: type[BaseModel],
    contexts: List[str],
    count: int = 10,
    *,
    seed: int | None = None,
) -> List[list[BaseModel]]:
    """Synchronous wrapper around :func:`generate_synthetic_data_batch`."""
    return _run_coro(
        generate_synthetic_data_batch(model_class, contexts, count=count, seed=seed)
    )


async def _generate_with_distribution_sampling(
    model_class: type[BaseModel],
    count: int,
    context: str,
    seed: int | None,
    prefilled: list[dict[str, Any]] | None = None,
    relational_context: list[dict[str, Any]] | None = None,
) -> list[BaseModel]:
    """
    Generate data using numpy sampling for distribution fields and LLM for the rest.

    This is the main generation function that:
    1. Extracts distribution specs and correlations from the model
    2. Samples distribution fields using numpy (with correlations if specified)
    3. Generates remaining fields with LLM (using sampled values as context)
    4. Merges and validates the results

    If no distribution specs are found, falls back to full LLM generation.

    ``prefilled`` supplies engine-provided per-record values (e.g. primary and
    foreign keys from relational generation). These are merged into each record
    and excluded from both numpy sampling and LLM generation.

    ``relational_context`` supplies per-record data about the rows a record's
    foreign keys point at (e.g. the referenced product's name and category). It
    is shown to the LLM as context so generated text is coherent with the
    related rows, but it is never stored as a field on the record itself.
    """
    # 1. Extract distribution specs from Annotated types (with type info for proper casting)
    dist_specs = LLMDrivenModelAnalyser.extract_distribution_specs_with_types(
        model_class
    )

    # 2. Extract correlations and cross-field constraints from model (if defined)
    correlations = _extract_correlations(model_class)
    constraints = _extract_constraints(model_class)

    # 3. One sampler for the whole call: top-up rounds continue its RNG stream
    # rather than restarting it, so retries draw fresh (non-repeating) values
    # while the result stays deterministic for a given seed.
    all_fields = set(model_class.model_fields.keys())
    sampler = DistributionSampler(seed=seed)

    async def build_raw(
        n: int,
        batch_prefilled: list[dict[str, Any]] | None,
        batch_relational_context: list[dict[str, Any]] | None,
    ) -> list[dict[str, Any]]:
        """Sample ``n`` records, merge engine keys, and fill LLM fields."""
        partial_records = sampler.sample_fields(
            dist_specs, n, correlations=correlations, constraints=constraints
        )
        prefilled_fields: set[str] = set()
        if batch_prefilled is not None:
            for record, extra in zip(partial_records, batch_prefilled, strict=True):
                record.update(extra)
                prefilled_fields.update(extra.keys())
        fields_to_generate = all_fields - (set(dist_specs.keys()) | prefilled_fields)
        if not fields_to_generate:
            return partial_records
        llm_outputs = await _generate_remaining_fields(
            model_class,
            partial_records,
            fields_to_generate,
            context,
            relational_context=batch_relational_context,
        )
        return _merge_records(partial_records, llm_outputs)

    # Relational path: primary/foreign keys are assigned per row by the engine
    # and cannot be regenerated here, so we cannot top up. Dropping a row would
    # break referential integrity (other tables' FKs may point at it), so any
    # validation failure is fatal rather than silently returning fewer rows.
    if prefilled is not None:
        raw = await build_raw(count, prefilled, relational_context)
        valid, failed = _validate_split(model_class, raw)
        if failed:
            raise ValueError(
                f"{len(failed)} of {count} generated {model_class.__name__} "
                "record(s) failed validation during relational generation; rows "
                "cannot be dropped without breaking referential integrity. "
                f"First error: {failed[0][1]}"
            )
        return valid

    # Standalone path: top up to `count`, regenerating only the shortfall each
    # round so validation failures don't silently shrink the batch.
    valid_records: list[BaseModel] = []
    total_failed = 0
    rounds_used = 0
    for _ in range(_MAX_TOPUP_ROUNDS):
        need = count - len(valid_records)
        if need <= 0:
            break
        rounds_used += 1
        raw = await build_raw(need, None, None)
        batch_valid, batch_failed = _validate_split(model_class, raw)
        valid_records.extend(batch_valid)
        total_failed += len(batch_failed)
        if not batch_valid:
            # A whole round produced nothing usable: the failure is systematic
            # (e.g. a validator rejecting the generated shape), so further rounds
            # would only burn LLM calls. Stop and report below.
            break

    if len(valid_records) < count:
        if not valid_records:
            raise ValueError(
                f"No valid {model_class.__name__} records could be generated: every "
                "record failed validation. Check the model's validators against the "
                "sampled and generated values."
            )
        raise ValueError(
            f"Could only generate {len(valid_records)} of {count} requested "
            f"{model_class.__name__} records: records kept failing validation "
            f"(gave up after {rounds_used} round(s)). Check the model's validators."
        )

    if total_failed:
        logger.warning(
            "Regenerated %d %s record(s) that failed validation to reach the "
            "requested count of %d.",
            total_failed,
            model_class.__name__,
            count,
        )
    return valid_records[:count]


async def _generate_remaining_fields(
    model_class: type[BaseModel],
    partial_records: list[dict[str, Any]],
    fields_to_generate: set[str],
    context: str,
    batch_size: int = 15,
    relational_context: list[dict[str, Any]] | None = None,
) -> list[dict[str, Any]]:
    """
    Use LLM to generate the remaining fields not covered by distributions.

    The LLM receives the partial records (with sampled values) as context,
    so it can generate coherent values for the remaining fields.

    Uses batching to avoid LLM output token limits for large record counts.
    """
    # Get LLM analysis for context (only once)
    analysis = await LLMDrivenModelAnalyser.analyse_model_for_generation(
        model_class, context=context, count=len(partial_records)
    )

    model_analysis = analysis.get("model_analysis", {})
    if isinstance(model_analysis, str):
        purpose = model_analysis
        domain = "business"
    else:
        purpose = model_analysis.get("purpose", f"{model_class.__name__} data")
        domain = model_analysis.get("domain", "general")

    # Extract validator docstrings to surface enforced constraints to the LLM
    validator_hints = _get_validator_hints_from_docstrings(model_class)

    # Build a schema for just the fields we need
    full_schema = model_class.model_json_schema()
    partial_schema = {
        "type": "array",
        "items": {
            "type": "object",
            "properties": {
                field: full_schema.get("properties", {}).get(field, {"type": "string"})
                for field in fields_to_generate
            },
            "required": list(fields_to_generate),
        },
    }

    client = get_client()

    # For display to the LLM, fold each record's related-row context into the
    # record shown in the prompt (under "related_records") so generated text can
    # be coherent with the rows its foreign keys point at. This never becomes a
    # stored field — only the fields in ``fields_to_generate`` are kept.
    display_records = list(partial_records)
    if relational_context is not None:
        display_records = [
            {**record, "related_records": ctx} if ctx else dict(record)
            for record, ctx in zip(partial_records, relational_context, strict=True)
        ]

    # Batch the records to avoid LLM output token limits
    batches = [
        display_records[i : i + batch_size]
        for i in range(0, len(display_records), batch_size)
    ]

    async def generate_batch(batch: list[dict[str, Any]]) -> list[dict[str, Any]]:
        prompt = load_prompt("partial_record_generation").format(
            count=len(batch),
            model_class=model_class.__name__,
            fields_to_generate=", ".join(sorted(fields_to_generate)),
            partial_records=json.dumps(batch, indent=2, default=str),
            validator_hints=validator_hints,
            purpose=purpose,
            domain=domain,
            context=context,
        )
        return await client.generate_structured(
            schema=partial_schema,
            prompt=prompt,
            count=len(batch),
        )

    try:
        # Run all batches concurrently
        batch_results = await asyncio.gather(*[generate_batch(b) for b in batches])
        # Flatten results
        return [record for batch in batch_results for record in batch]
    except Exception as e:
        raise ValueError(f"Failed to generate remaining fields: {e}") from e


def _merge_records(
    sampled: list[dict[str, Any]],
    generated: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Merge sampled distribution values with LLM-generated values.

    If LLM generated more records than needed, truncates to match.
    If LLM generated fewer, raises an error.
    """
    if len(generated) > len(sampled):
        # LLM generated extra records - truncate to match
        logger.warning(
            "LLM generated %d records but only %d were requested; truncating extras.",
            len(generated),
            len(sampled),
        )
        generated = generated[: len(sampled)]
    elif len(generated) < len(sampled):
        raise ValueError(
            f"Record count mismatch: {len(sampled)} sampled vs {len(generated)} generated. "
            "LLM generated fewer records than requested."
        )

    return [{**s, **g} for s, g in zip(sampled, generated, strict=False)]


def _validate_split(
    model_class: type[BaseModel], raw_data: list[dict[str, Any]]
) -> tuple[list[BaseModel], list[tuple[dict[str, Any], ValidationError]]]:
    """Partition raw dicts into validated instances and ``(dict, error)`` failures.

    Never raises: the caller decides whether to top up, retry, or fail based on
    how many records validated.
    """
    valid: list[BaseModel] = []
    failed: list[tuple[dict[str, Any], ValidationError]] = []
    for item in raw_data:
        try:
            valid.append(model_class(**item))
        except ValidationError as e:
            failed.append((item, e))
            logger.debug("Validation error for item %r: %s", item, e)
    return valid, failed


def _iter_validators(model_class: type[BaseModel]) -> list[tuple[str, str]]:
    """Yield ``(validator_name, docstring)`` for every validator on the model.

    Pydantic v2 records validators on ``__pydantic_decorators__`` rather than as
    attributes discoverable via ``dir()``.
    """
    decorators = model_class.__pydantic_decorators__
    validators: list[tuple[str, str]] = []
    for name, field_validator in decorators.field_validators.items():
        validators.append((name, field_validator.func.__doc__ or ""))
    for name, model_validator in decorators.model_validators.items():
        validators.append((name, model_validator.func.__doc__ or ""))
    return validators


def _get_validator_hints_from_docstrings(model_class: type[BaseModel]) -> str:
    """Extract validator hints from model docstrings and validators."""
    hints = []

    # Check for field validators with specific docstrings
    for name, doc in _iter_validators(model_class):
        if doc:
            hints.append(f"- **{name}**: {doc.strip()}")

    return "\n".join(hints) if hints else ""


def _extract_correlations(model_class: type[BaseModel]) -> Correlations | None:
    """
    Extract correlation specifications from a model class.

    Looks for a __correlations__ class attribute that should be a Correlations instance.

    Args:
        model_class: The Pydantic model class

    Returns:
        Correlations instance if found, None otherwise

    Example:
        class Employee(BaseModel):
            age: Annotated[int, Uniform(min=22, max=65)]
            salary: Annotated[float, Normal(mean=75000, std=20000)]

            __correlations__ = Correlations(
                ("age", "salary", 0.5),
            )
    """
    correlations = getattr(model_class, "__correlations__", None)

    if correlations is None:
        return None

    if isinstance(correlations, Correlations):
        return correlations

    # Support dict format as well for convenience
    if isinstance(correlations, dict):
        specs = [(k[0], k[1], v) for k, v in correlations.items()]
        return Correlations(*specs)

    return None


def _extract_constraints(model_class: type[BaseModel]) -> Constraints | None:
    """
    Extract cross-field constraints from a model class.

    Looks for a ``__constraints__`` class attribute that should be a
    ``Constraints`` instance (e.g. containing ``Ordering(...)`` constraints).

    Returns:
        Constraints instance if found, None otherwise.
    """
    constraints = getattr(model_class, "__constraints__", None)
    if isinstance(constraints, Constraints):
        return constraints
    return None
