import asyncio
import inspect
import json
import logging
import re
from collections.abc import Coroutine
from typing import Any, List, TypeVar

from pydantic import BaseModel, ValidationError

from .distributions import Correlations
from .llm import get_client
from .llm_driven_analyser import LLMDrivenModelAnalyser
from .prompts import load_prompt
from .sampler import DistributionSampler

logger = logging.getLogger("gendantic")

_T = TypeVar("_T")


def _run_coro(coro: Coroutine[Any, Any, _T]) -> _T:
    """Run an async coroutine from synchronous code.

    Raises a clear error if called from within an already-running event loop
    (e.g. a Jupyter cell), where the caller should await the async API instead.
    """
    try:
        asyncio.get_running_loop()
    except RuntimeError:
        return asyncio.run(coro)

    coro.close()
    raise RuntimeError(
        "A synchronous gendantic function was called from inside a running "
        "event loop. Use the async API instead (e.g. "
        "`await generate_synthetic_data(...)`)."
    )


async def generate_synthetic_data(
    model_class: type[BaseModel],
    count: int = 10,
    *,
    context: str = "general",
    seed: int | None = None,
) -> list[BaseModel]:
    """
    Generate synthetic data records for a Pydantic model.

    Uses numpy sampling for fields with distribution specifications (via Annotated types)
    to guarantee statistical compliance. Remaining fields are generated by the LLM with
    the sampled values as context for coherence.

    Args:
        model_class: The Pydantic model class to generate data for
        count: Number of records to generate
        context: Optional context about the intended use case for better generation
        seed: Random seed for reproducible sampling of distribution fields

    Returns:
        List of model instances with synthetic data

    Examples:
        # Basic generation
        users = await generate_synthetic_data(User, count=100)

        # Context-aware generation
        employees = await generate_synthetic_data(
            Employee,
            count=50,
            context="UK tech startup with remote-first culture"
        )

        # With distribution specifications
        from typing import Annotated
        from gendantic import Normal, Categorical

        class Employee(BaseModel):
            salary: Annotated[int, Normal(mean=50000, std=15000)]
            department: Annotated[str, Categorical(weights={"Eng": 0.6, "Sales": 0.4})]
            name: str  # Generated by LLM

        # salary and department sampled by numpy, name generated by LLM
        employees = await generate_synthetic_data(Employee, count=100, seed=42)
    """

    if context == "general":
        context = f"Modern business using {model_class.__name__} data model"
    return await _generate_with_distribution_sampling(model_class, count, context, seed)


async def generate_synthetic_data_batch(
    model_class: type[BaseModel],
    contexts: List[str],
    count: int = 10,
    *,
    seed: int | None = None,
) -> List[list[BaseModel]]:
    """
    Generate multiple batches of synthetic data with different contexts concurrently.

    Args:
        model_class: The Pydantic model class to generate data for
        contexts: List of contexts for different batches
        count: Number of records per batch
        seed: Random seed for reproducible sampling of distribution fields

    Returns:
        List of lists, each containing model instances for one context

    Examples:
        contexts = ["UK bank", "US startup", "German manufacturing"]
        batches = await generate_synthetic_data_batch(Employee, contexts, count=20)
    """

    tasks = [
        generate_synthetic_data(model_class, count, context=context, seed=seed)
        for context in contexts
    ]
    return await asyncio.gather(*tasks)


def generate_synthetic_data_sync(
    model_class: type[BaseModel],
    count: int = 10,
    *,
    context: str = "general",
    seed: int | None = None,
) -> list[BaseModel]:
    """Synchronous wrapper around :func:`generate_synthetic_data`.

    Convenient for scripts and REPL use where you don't want to manage an event
    loop. Must not be called from within a running event loop (await the async
    version there instead).

    Examples:
        employees = generate_synthetic_data_sync(Employee, count=100, seed=42)
    """
    return _run_coro(
        generate_synthetic_data(model_class, count, context=context, seed=seed)
    )


def generate_synthetic_data_batch_sync(
    model_class: type[BaseModel],
    contexts: List[str],
    count: int = 10,
    *,
    seed: int | None = None,
) -> List[list[BaseModel]]:
    """Synchronous wrapper around :func:`generate_synthetic_data_batch`."""
    return _run_coro(
        generate_synthetic_data_batch(model_class, contexts, count=count, seed=seed)
    )


async def _generate_with_distribution_sampling(
    model_class: type[BaseModel],
    count: int,
    context: str,
    seed: int | None,
    prefilled: list[dict[str, Any]] | None = None,
    relational_context: list[dict[str, Any]] | None = None,
) -> list[BaseModel]:
    """
    Generate data using numpy sampling for distribution fields and LLM for the rest.

    This is the main generation function that:
    1. Extracts distribution specs and correlations from the model
    2. Samples distribution fields using numpy (with correlations if specified)
    3. Generates remaining fields with LLM (using sampled values as context)
    4. Merges and validates the results

    If no distribution specs are found, falls back to full LLM generation.

    ``prefilled`` supplies engine-provided per-record values (e.g. primary and
    foreign keys from relational generation). These are merged into each record
    and excluded from both numpy sampling and LLM generation.

    ``relational_context`` supplies per-record data about the rows a record's
    foreign keys point at (e.g. the referenced product's name and category). It
    is shown to the LLM as context so generated text is coherent with the
    related rows, but it is never stored as a field on the record itself.
    """
    # 1. Extract distribution specs from Annotated types (with type info for proper casting)
    dist_specs = LLMDrivenModelAnalyser.extract_distribution_specs_with_types(
        model_class
    )

    # 2. Extract correlations from model (if defined)
    correlations = _extract_correlations(model_class)

    # 3. Sample distribution fields with numpy (using correlations if present)
    sampler = DistributionSampler(seed=seed)
    partial_records = sampler.sample_fields(
        dist_specs, count, correlations=correlations
    )

    # 3a. Merge in any engine-prefilled fields (primary/foreign keys)
    prefilled_fields: set[str] = set()
    if prefilled is not None:
        for record, extra in zip(partial_records, prefilled, strict=True):
            record.update(extra)
            prefilled_fields.update(extra.keys())

    # 4. Identify fields that need LLM generation
    all_fields = set(model_class.model_fields.keys())
    sampled_fields = set(dist_specs.keys()) | prefilled_fields
    fields_to_generate = all_fields - sampled_fields

    if fields_to_generate:
        # 4. LLM generates remaining fields with sampled values as context
        llm_outputs = await _generate_remaining_fields(
            model_class,
            partial_records,
            fields_to_generate,
            context,
            relational_context=relational_context,
        )
        # 5. Merge sampled + generated
        records = _merge_records(partial_records, llm_outputs)
    else:
        # All fields covered by distributions - no LLM needed
        records = partial_records

    # 6. Validate and convert to Pydantic models
    return _validate_and_convert(model_class, records)


async def _generate_remaining_fields(
    model_class: type[BaseModel],
    partial_records: list[dict[str, Any]],
    fields_to_generate: set[str],
    context: str,
    batch_size: int = 15,
    relational_context: list[dict[str, Any]] | None = None,
) -> list[dict[str, Any]]:
    """
    Use LLM to generate the remaining fields not covered by distributions.

    The LLM receives the partial records (with sampled values) as context,
    so it can generate coherent values for the remaining fields.

    Uses batching to avoid LLM output token limits for large record counts.
    """
    # Get LLM analysis for context (only once)
    analysis = await LLMDrivenModelAnalyser.analyse_model_for_generation(
        model_class, context=context, count=len(partial_records)
    )

    model_analysis = analysis.get("model_analysis", {})
    if isinstance(model_analysis, str):
        purpose = model_analysis
        domain = "business"
    else:
        purpose = model_analysis.get("purpose", f"{model_class.__name__} data")
        domain = model_analysis.get("domain", "general")

    # Extract validator requirements
    critical_requirements = _extract_critical_validation_requirements(model_class)
    validator_hints = _get_validator_hints_from_docstrings(model_class)

    # Build a schema for just the fields we need
    full_schema = model_class.model_json_schema()
    partial_schema = {
        "type": "array",
        "items": {
            "type": "object",
            "properties": {
                field: full_schema.get("properties", {}).get(field, {"type": "string"})
                for field in fields_to_generate
            },
            "required": list(fields_to_generate),
        },
    }

    client = get_client()

    # For display to the LLM, fold each record's related-row context into the
    # record shown in the prompt (under "related_records") so generated text can
    # be coherent with the rows its foreign keys point at. This never becomes a
    # stored field — only the fields in ``fields_to_generate`` are kept.
    display_records = list(partial_records)
    if relational_context is not None:
        display_records = [
            {**record, "related_records": ctx} if ctx else dict(record)
            for record, ctx in zip(partial_records, relational_context, strict=True)
        ]

    # Batch the records to avoid LLM output token limits
    batches = [
        display_records[i : i + batch_size]
        for i in range(0, len(display_records), batch_size)
    ]

    async def generate_batch(batch: list[dict[str, Any]]) -> list[dict[str, Any]]:
        prompt = load_prompt("partial_record_generation").format(
            count=len(batch),
            model_class=model_class.__name__,
            fields_to_generate=", ".join(sorted(fields_to_generate)),
            partial_records=json.dumps(batch, indent=2, default=str),
            critical_requirements=critical_requirements,
            validator_hints=validator_hints,
            purpose=purpose,
            domain=domain,
            context=context,
        )
        return await client.generate_structured(
            schema=partial_schema,
            prompt=prompt,
            count=len(batch),
        )

    try:
        # Run all batches concurrently
        batch_results = await asyncio.gather(*[generate_batch(b) for b in batches])
        # Flatten results
        return [record for batch in batch_results for record in batch]
    except Exception as e:
        raise ValueError(f"Failed to generate remaining fields: {e}") from e


def _merge_records(
    sampled: list[dict[str, Any]],
    generated: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Merge sampled distribution values with LLM-generated values.

    If LLM generated more records than needed, truncates to match.
    If LLM generated fewer, raises an error.
    """
    if len(generated) > len(sampled):
        # LLM generated extra records - truncate to match
        logger.warning(
            "LLM generated %d records but only %d were requested; truncating extras.",
            len(generated),
            len(sampled),
        )
        generated = generated[: len(sampled)]
    elif len(generated) < len(sampled):
        raise ValueError(
            f"Record count mismatch: {len(sampled)} sampled vs {len(generated)} generated. "
            "LLM generated fewer records than requested."
        )

    return [{**s, **g} for s, g in zip(sampled, generated, strict=False)]


def _validate_and_convert(
    model_class: type[BaseModel], raw_data: list[dict[str, Any]]
) -> list[BaseModel]:
    """Validate and convert raw data to model instances."""

    validated_data = []
    failures = 0
    for item in raw_data:
        try:
            instance = model_class(**item)
            validated_data.append(instance)
        except ValidationError as e:
            failures += 1
            logger.debug("Validation error for item %r: %s", item, e)
            continue

    if not validated_data:
        raise ValueError("No valid data was generated")

    if failures:
        logger.warning(
            "%d of %d generated %s record(s) failed validation and were dropped; "
            "returning %d valid record(s).",
            failures,
            len(raw_data),
            model_class.__name__,
            len(validated_data),
        )

    return validated_data


def _get_validator_hints_from_docstrings(model_class: type[BaseModel]) -> str:
    """Extract validator hints from model docstrings and validators."""
    hints = []

    # Check for field validators with specific docstrings
    for attr_name in dir(model_class):
        attr = getattr(model_class, attr_name)
        if hasattr(attr, "__pydantic_validator__") or "validator" in attr_name:
            doc = getattr(attr, "__doc__", "")
            if doc:
                hints.append(f"- **{attr_name}**: {doc.strip()}")

    return "\n".join(hints) if hints else ""


def _extract_critical_validation_requirements(model_class: type[BaseModel]) -> str:
    """Extract critical validation requirements by examining the model."""

    requirements = []

    # Direct inspection of specific validation patterns
    for attr_name in dir(model_class):
        attr = getattr(model_class, attr_name)

        # Check for field validators
        if (
            hasattr(attr, "__pydantic_validator__")
            or callable(attr)
            and "validator" in attr_name
        ):
            doc = getattr(attr, "__doc__", "")

            # Extract specific domain requirements from docstrings and method names
            if "email" in attr_name and (
                "company" in attr_name or "domain" in doc.lower()
            ):
                if "@" in doc:
                    # Extract domain from docstring
                    domain_match = re.search(r"@([a-zA-Z0-9.-]+\.com)", doc)
                    if domain_match:
                        domain = domain_match.group(1)
                        requirements.append(
                            f"- **CRITICAL EMAIL DOMAIN**: ALL emails must end with @{domain} (validator enforced)"
                        )
                elif "company" in doc.lower() or "work" in doc.lower():
                    requirements.append(
                        "- **CRITICAL EMAIL DOMAIN**: ALL emails must use company domain (validator enforced)"
                    )

            # Generic validator documentation
            if doc and len(doc.strip()) > 10:
                field_match = re.search(r"(\w+)", attr_name)
                field_name = field_match.group(1) if field_match else "field"
                requirements.append(
                    f"- **{field_name.upper()} VALIDATION**: {doc.strip()}"
                )

    # Also check source code for validation error messages
    try:
        source = inspect.getsource(model_class)
        if "@" in source and "ValueError" in source:
            # Extract domain requirements from validation error messages
            domain_matches = re.findall(r"@([a-zA-Z0-9.-]+\.com)", source)
            for domain in set(domain_matches):
                requirements.append(
                    f"- **MANDATORY EMAIL DOMAIN**: ALL generated emails MUST use @{domain}"
                )
    except (OSError, TypeError):
        pass

    return "\n".join(requirements) if requirements else ""


def _extract_correlations(model_class: type[BaseModel]) -> Correlations | None:
    """
    Extract correlation specifications from a model class.

    Looks for a __correlations__ class attribute that should be a Correlations instance.

    Args:
        model_class: The Pydantic model class

    Returns:
        Correlations instance if found, None otherwise

    Example:
        class Employee(BaseModel):
            age: Annotated[int, Uniform(min=22, max=65)]
            salary: Annotated[float, Normal(mean=75000, std=20000)]

            __correlations__ = Correlations(
                ("age", "salary", 0.5),
            )
    """
    correlations = getattr(model_class, "__correlations__", None)

    if correlations is None:
        return None

    if isinstance(correlations, Correlations):
        return correlations

    # Support dict format as well for convenience
    if isinstance(correlations, dict):
        specs = [(k[0], k[1], v) for k, v in correlations.items()]
        return Correlations(*specs)

    return None
