"""Relational (multi-model) synthetic data generation.

Adds primary/foreign-key field specs and a ``generate_dataset`` orchestrator so
several related Pydantic models can be generated together with referential
integrity: primary keys are unique, and every foreign key points at a real
primary key of the referenced model.

Example:
    from typing import Annotated
    from pydantic import BaseModel
    from gendantic import PrimaryKey, ForeignKey, Normal, generate_dataset

    class Customer(BaseModel):
        id: Annotated[int, PrimaryKey()]
        name: str

    class Order(BaseModel):
        id: Annotated[int, PrimaryKey()]
        customer_id: Annotated[int, ForeignKey(Customer)]
        amount: Annotated[float, Normal(mean=200, std=80)]

    dataset = await generate_dataset({Customer: 100, Order: 500}, seed=42)
    customers = dataset[Customer]   # 100 rows, unique ids
    orders = dataset[Order]         # 500 rows, each customer_id in customers
"""

import logging
import uuid
from collections.abc import Iterator
from dataclasses import dataclass
from typing import TYPE_CHECKING, Annotated, Any, get_args, get_origin

import numpy as np
from pydantic import BaseModel

logger = logging.getLogger("gendantic")

if TYPE_CHECKING:
    import pandas as pd


@dataclass(frozen=True)
class PrimaryKey:
    """Marks a field as the model's primary key.

    Values are generated by the engine (never asked of the LLM) and are unique
    within the generated rows.

    Args:
        strategy: How to generate key values.
            - ``"auto"`` (default): sequential integers for ``int`` fields,
              random UUID hex strings for ``str`` fields.
            - ``"sequential"``: integers ``1..count``.
            - ``"uuid"``: random UUID hex strings.
    """

    strategy: str = "auto"

    def generate(
        self, count: int, base_type: type, rng: np.random.Generator
    ) -> list[Any]:
        """Generate ``count`` unique primary-key values for the given field type."""
        strategy = self.strategy
        if strategy == "auto":
            strategy = "uuid" if base_type is str else "sequential"

        if strategy == "sequential":
            return list(range(1, count + 1))
        if strategy == "uuid":
            # Draw UUID bytes from the seeded rng so datasets are reproducible.
            return [uuid.UUID(bytes=rng.bytes(16)).hex for _ in range(count)]

        raise ValueError(
            f"Unknown PrimaryKey strategy {strategy!r}; "
            "expected 'auto', 'sequential', or 'uuid'."
        )


@dataclass(frozen=True)
class ForeignKey:
    """Marks a field as a reference to another model's primary key.

    The engine assigns each row a primary-key value drawn uniformly at random
    from the referenced model's generated rows, guaranteeing referential
    integrity.

    Args:
        model: The referenced Pydantic model class (must also be generated), or
            its class name as a string. Use a string forward reference for
            self-references or mutual references, where the class isn't yet
            defined in its own body — e.g. ``ForeignKey("Employee")`` for a
            ``manager_id`` on ``Employee``.
        field: Name of the referenced primary-key field. Defaults to the
            referenced model's ``PrimaryKey`` field.
        nullable: If True, some values are left as ``None``.
        null_probability: Fraction of values set to ``None`` when ``nullable``.
    """

    model: type[BaseModel] | str
    field: str | None = None
    nullable: bool = False
    null_probability: float = 0.1


@dataclass(frozen=True)
class ForeignKeySpec:
    """A (possibly composite) foreign key declared at the class level.

    Use this for **composite** foreign keys, where several columns together
    reference a parent's composite primary key. Declare them in a
    ``__foreign_keys__`` class attribute (a list of ``ForeignKeySpec``). For the
    common single-column case, the per-field :class:`ForeignKey` annotation is
    simpler.

    Args:
        columns: Local column name(s) forming the foreign key. A bare string is
            treated as a single-column key.
        model: The referenced model class, or its name as a string forward
            reference.
        references: The parent column name(s) referenced, positionally aligned
            with ``columns``. Defaults to the parent's primary-key columns.
        nullable: If True, some rows leave the whole key ``None`` (ignored for
            columns that are also part of this model's primary key).
        null_probability: Fraction of rows set to ``None`` when ``nullable``.

    Example:
        class OrderItem(BaseModel):
            order_id: int
            product_id: int
            __primary_key__ = ("order_id", "product_id")
            __foreign_keys__ = [
                ForeignKeySpec(columns="order_id", model="Order"),
                ForeignKeySpec(columns="product_id", model="Product"),
            ]
    """

    columns: tuple[str, ...] | str
    model: type[BaseModel] | str
    references: tuple[str, ...] | str | None = None
    nullable: bool = False
    null_probability: float = 0.1


class Dataset:
    """A generated collection of related tables, keyed by model class.

    Behaves like a read-only mapping: ``dataset[Customer]`` returns the list of
    generated ``Customer`` instances.
    """

    def __init__(self, tables: dict[type[BaseModel], list[BaseModel]]):
        self._tables = tables

    def __getitem__(self, model: type[BaseModel]) -> list[BaseModel]:
        return self._tables[model]

    def __iter__(self) -> Iterator[type[BaseModel]]:
        return iter(self._tables)

    def __len__(self) -> int:
        return len(self._tables)

    def __contains__(self, model: object) -> bool:
        return model in self._tables

    def items(self) -> Iterator[tuple[type[BaseModel], list[BaseModel]]]:
        return iter(self._tables.items())

    def to_dataframes(self) -> dict[str, "pd.DataFrame"]:
        """Convert every table to a pandas DataFrame, keyed by model name."""
        from .export import to_dataframe

        return {
            model.__name__: to_dataframe(records)
            for model, records in self._tables.items()
        }


# --- Internal representations ---------------------------------------------
#
# A primary key is one or more columns; a foreign key is one or more columns
# referencing a parent's primary-key columns. Single-column keys (the common
# case) are declared with per-field ``PrimaryKey`` / ``ForeignKey`` annotations;
# composite keys use the class-level ``__primary_key__`` tuple and
# ``__foreign_keys__`` list of :class:`ForeignKeySpec`. Both are normalised into
# the tuple-based representations below before generation.


@dataclass(frozen=True)
class _PKColumn:
    field: str
    base_type: type
    spec: PrimaryKey


@dataclass(frozen=True)
class _FKDecl:
    """An unresolved foreign key: column names plus an (as-yet-unresolved) target."""

    columns: tuple[str, ...]
    target_ref: type[BaseModel] | str
    references: tuple[str, ...] | None
    nullable: bool
    null_probability: float


@dataclass(frozen=True)
class _ResolvedFK:
    """A foreign key with its target class resolved and referenced columns filled."""

    columns: tuple[str, ...]
    target: type[BaseModel]
    ref_columns: tuple[str, ...]
    nullable: bool
    null_probability: float


def _field_base_type(model_class: type[BaseModel], name: str) -> type:
    annotation = getattr(model_class, "__annotations__", {}).get(name)
    if annotation is None:
        return str
    if get_origin(annotation) is Annotated:
        base = get_args(annotation)[0]
        return base if isinstance(base, type) else str
    return annotation if isinstance(annotation, type) else str


def _annotated_pks(model_class: type[BaseModel]) -> list[tuple[str, PrimaryKey, type]]:
    """Return ``(field, PrimaryKey, base_type)`` for each PK-annotated field."""
    out: list[tuple[str, PrimaryKey, type]] = []
    for field_name, annotation in getattr(model_class, "__annotations__", {}).items():
        if get_origin(annotation) is Annotated:
            args = get_args(annotation)
            for arg in args[1:]:
                if isinstance(arg, PrimaryKey):
                    out.append((field_name, arg, args[0]))
                    break
    return out


def _primary_key_columns(model_class: type[BaseModel]) -> list[_PKColumn]:
    """Return the model's primary-key columns, in order.

    Supports composite keys via a ``__primary_key__`` class attribute (a tuple of
    column names); otherwise every field carrying a ``PrimaryKey`` annotation
    forms the key, in declaration order.
    """
    annotated = {field: (spec, base) for field, spec, base in _annotated_pks(model_class)}
    declared = getattr(model_class, "__primary_key__", None)
    if declared is not None:
        names: tuple[str, ...] = (
            (declared,) if isinstance(declared, str) else tuple(declared)
        )
        cols: list[_PKColumn] = []
        for name in names:
            if name in annotated:
                spec, base = annotated[name]
            else:
                spec, base = PrimaryKey(), _field_base_type(model_class, name)
            cols.append(_PKColumn(name, base, spec))
        return cols
    return [_PKColumn(field, base, spec) for field, (spec, base) in annotated.items()]


def _primary_key_names(model_class: type[BaseModel]) -> list[str]:
    return [c.field for c in _primary_key_columns(model_class)]


def extract_primary_key(
    model_class: type[BaseModel],
) -> tuple[str, PrimaryKey, type] | None:
    """Return ``(field_name, PrimaryKey, base_type)`` for the model's PK, if any.

    For composite primary keys this returns the first key column; use
    :func:`_primary_key_columns` for the full key.
    """
    cols = _primary_key_columns(model_class)
    if not cols:
        return None
    first = cols[0]
    return first.field, first.spec, first.base_type


def extract_foreign_keys(model_class: type[BaseModel]) -> dict[str, ForeignKey]:
    """Return a mapping of ``field_name -> ForeignKey`` for per-field annotations."""
    foreign_keys: dict[str, ForeignKey] = {}
    annotations = getattr(model_class, "__annotations__", {})
    for field_name, annotation in annotations.items():
        if get_origin(annotation) is Annotated:
            args = get_args(annotation)
            for arg in args[1:]:
                if isinstance(arg, ForeignKey):
                    foreign_keys[field_name] = arg
                    break
    return foreign_keys


def _foreign_key_decls(model_class: type[BaseModel]) -> list[_FKDecl]:
    """Collect every foreign key on a model, from annotations and class attribute.

    Single-column keys come from per-field :class:`ForeignKey` annotations;
    composite keys come from a ``__foreign_keys__`` list of :class:`ForeignKeySpec`.
    """
    decls: list[_FKDecl] = []
    for field_name, fk in extract_foreign_keys(model_class).items():
        refs = (fk.field,) if fk.field is not None else None
        decls.append(
            _FKDecl((field_name,), fk.model, refs, fk.nullable, fk.null_probability)
        )
    for spec in getattr(model_class, "__foreign_keys__", None) or []:
        columns = (
            (spec.columns,) if isinstance(spec.columns, str) else tuple(spec.columns)
        )
        if spec.references is None:
            references: tuple[str, ...] | None = None
        elif isinstance(spec.references, str):
            references = (spec.references,)
        else:
            references = tuple(spec.references)
        decls.append(
            _FKDecl(
                columns, spec.model, references, spec.nullable, spec.null_probability
            )
        )
    return decls


def _resolve_fk_model(
    target_ref: type[BaseModel] | str,
    referrer_name: str,
    label: str,
    by_name: dict[str, type[BaseModel]],
) -> type[BaseModel]:
    """Resolve a foreign key's target to a model class in the dataset.

    Accepts either a class or a string forward reference (the target's class
    name). Raises ValueError if the target isn't part of the dataset.
    """
    if isinstance(target_ref, str):
        resolved = by_name.get(target_ref)
        if resolved is None:
            raise ValueError(
                f"{referrer_name}.{label} references {target_ref!r}, "
                f"which is not included in the dataset. Add it with a count."
            )
        return resolved
    if target_ref not in by_name.values():
        raise ValueError(
            f"{referrer_name}.{label} references {target_ref.__name__}, "
            f"which is not included in the dataset. Add it with a count."
        )
    return target_ref


def _resolve_foreign_keys(
    model_class: type[BaseModel],
    by_name: dict[str, type[BaseModel]],
) -> list[_ResolvedFK]:
    """Resolve every foreign key on a model against the dataset's models."""
    resolved: list[_ResolvedFK] = []
    for decl in _foreign_key_decls(model_class):
        label = "/".join(decl.columns)
        target = _resolve_fk_model(decl.target_ref, model_class.__name__, label, by_name)
        parent_pk = _primary_key_names(target)
        if not parent_pk:
            raise ValueError(
                f"{model_class.__name__}.{label} references {target.__name__}, "
                f"which has no primary key."
            )
        ref_columns = decl.references or tuple(parent_pk)
        if len(ref_columns) != len(decl.columns):
            raise ValueError(
                f"{model_class.__name__}.{label} has {len(decl.columns)} column(s) "
                f"but references {len(ref_columns)} column(s) on {target.__name__}."
            )
        if set(ref_columns) != set(parent_pk):
            raise ValueError(
                f"{model_class.__name__}.{label} must reference the full primary "
                f"key of {target.__name__} ({', '.join(parent_pk)})."
            )
        resolved.append(
            _ResolvedFK(
                decl.columns, target, ref_columns, decl.nullable, decl.null_probability
            )
        )
    return resolved


def _resolve_generation_order(
    models: list[type[BaseModel]],
) -> list[type[BaseModel]]:
    """Topologically sort models so referenced (parent) models come first.

    Raises ValueError on a cyclic foreign-key dependency, or if a foreign key
    references a model that is not being generated.
    """
    by_name = {m.__name__: m for m in models}
    dependencies: dict[type[BaseModel], set[type[BaseModel]]] = {
        m: set() for m in models
    }
    for model in models:
        for fk in _resolve_foreign_keys(model, by_name):
            if fk.target is not model:
                dependencies[model].add(fk.target)

    order: list[type[BaseModel]] = []
    resolved: set[type[BaseModel]] = set()
    while len(order) < len(models):
        progressed = False
        for model in models:
            if model in resolved:
                continue
            if dependencies[model] <= resolved:
                order.append(model)
                resolved.add(model)
                progressed = True
        if not progressed:
            remaining = [m.__name__ for m in models if m not in resolved]
            raise ValueError(
                f"Cyclic foreign-key dependency among models: {', '.join(remaining)}"
            )
    return order


def _write_fk(
    row: dict[str, Any],
    fk: _ResolvedFK,
    parent_tuple: tuple[Any, ...],
    parent_pk_names: list[str],
) -> None:
    """Copy the referenced parent's key values into this row's FK columns."""
    value_by_parent_col = dict(zip(parent_pk_names, parent_tuple, strict=True))
    for local_col, ref_col in zip(fk.columns, fk.ref_columns, strict=True):
        row[local_col] = value_by_parent_col[ref_col]


def _sample_distinct_combos(
    pool_sizes: list[int], count: int, rng: np.random.Generator
) -> list[tuple[int, ...]]:
    """Sample up to ``count`` distinct index combinations across parent pools.

    Used for join tables whose primary key is made up of its foreign keys: each
    row must be a distinct combination of parents. Returns fewer than ``count``
    combinations only when the space of combinations is itself smaller.
    """
    total = 1
    for size in pool_sizes:
        total *= size
    want = min(count, total)
    if total == 0:
        return []
    if total <= 200_000:
        import itertools

        all_combos = list(itertools.product(*[range(size) for size in pool_sizes]))
        chosen = rng.choice(len(all_combos), size=want, replace=False)
        return [all_combos[int(i)] for i in chosen]
    seen: set[tuple[int, ...]] = set()
    out: list[tuple[int, ...]] = []
    while len(out) < want:
        combo = tuple(int(rng.integers(size)) for size in pool_sizes)
        if combo not in seen:
            seen.add(combo)
            out.append(combo)
    return out


def _owned_pk_is_unique(
    owned: list[_PKColumn], owned_values: dict[str, list[Any]], count: int
) -> bool:
    """True if any owned PK column already yields ``count`` distinct values."""
    return any(len(set(owned_values[c.field])) == count for c in owned)


def _generate_keys(
    model_class: type[BaseModel],
    count: int,
    pk_cols: list[_PKColumn],
    resolved_fks: list[_ResolvedFK],
    pk_pools: dict[type[BaseModel], list[tuple[Any, ...]]],
    tables: dict[type[BaseModel], list[BaseModel]],
    rng: np.random.Generator,
) -> tuple[
    list[dict[str, Any]], list[tuple[Any, ...]] | None, list[dict[str, Any]], int
]:
    """Assign primary and foreign keys for one model's rows.

    Returns ``(prefilled_rows, pk_pool, relational_context, count)``. ``count``
    may be reduced when a join-table primary key has fewer possible distinct
    combinations than requested.
    """
    pk_names = [c.field for c in pk_cols]
    pk_name_set = set(pk_names)
    fk_covered = {col for fk in resolved_fks for col in fk.columns}
    # FKs that (partly) form the primary key vs. plain FKs.
    pk_fks = [fk for fk in resolved_fks if any(c in pk_name_set for c in fk.columns)]
    plain_fks = [fk for fk in resolved_fks if fk not in pk_fks]
    owned_pk = [c for c in pk_cols if c.field not in fk_covered]

    prefilled: list[dict[str, Any]] = [{} for _ in range(count)]

    # --- Primary key ---
    if pk_cols:
        owned_values = {
            c.field: c.spec.generate(count, c.base_type, rng) for c in owned_pk
        }
        owned_unique = _owned_pk_is_unique(owned_pk, owned_values, count)

        if pk_fks and not owned_unique:
            # Join-table style: the key is (partly) its foreign keys, so we must
            # pick distinct combinations of the referenced parents.
            pool_sizes = [len(pk_pools[fk.target]) for fk in pk_fks]
            combos = _sample_distinct_combos(pool_sizes, count, rng)
            if len(combos) < count:
                logger.warning(
                    "%s: only %d distinct primary-key combinations are possible "
                    "(requested %d); generating %d rows.",
                    model_class.__name__,
                    len(combos),
                    count,
                    len(combos),
                )
                count = len(combos)
                prefilled = prefilled[:count]
                owned_values = {k: v[:count] for k, v in owned_values.items()}
            for row, combo in zip(prefilled, combos, strict=True):
                for fk, pool_idx in zip(pk_fks, combo, strict=True):
                    _write_fk(
                        row,
                        fk,
                        pk_pools[fk.target][pool_idx],
                        _primary_key_names(fk.target),
                    )
        else:
            # Owned columns guarantee uniqueness (or there are no PK-forming FKs):
            # pick any parent for the PK-forming FKs at random.
            for fk in pk_fks:
                pool = pk_pools[fk.target]
                parent_pk_names = _primary_key_names(fk.target)
                for row in prefilled:
                    idx = int(rng.integers(len(pool)))
                    _write_fk(row, fk, pool[idx], parent_pk_names)

        for c in owned_pk:
            for row, value in zip(prefilled, owned_values[c.field], strict=True):
                row[c.field] = value

        pk_pool: list[tuple[Any, ...]] | None = [
            tuple(row[name] for name in pk_names) for row in prefilled
        ]
    else:
        pk_pool = None

    # Pools available for FK assignment, including this model's own pool so that
    # self-referential foreign keys can be satisfied.
    pools = dict(pk_pools)
    if pk_pool is not None:
        pools[model_class] = pk_pool

    # --- Plain (non-PK) foreign keys ---
    for fk in plain_fks:
        pool = pools[fk.target]
        parent_pk_names = _primary_key_names(fk.target)
        for row in prefilled:
            if fk.nullable and rng.random() < fk.null_probability:
                for col in fk.columns:
                    row[col] = None
            else:
                idx = int(rng.integers(len(pool)))
                _write_fk(row, fk, pool[idx], parent_pk_names)

    # --- Relational context for the LLM ---
    relational_context: list[dict[str, Any]] = [{} for _ in range(count)]
    for fk in resolved_fks:
        _attach_relational_context(
            relational_context, prefilled, fk, pools, tables.get(fk.target, [])
        )
    return prefilled, pk_pool, relational_context, count


def _attach_relational_context(
    relational_context: list[dict[str, Any]],
    prefilled: list[dict[str, Any]],
    fk: _ResolvedFK,
    pk_pools: dict[type[BaseModel], list[tuple[Any, ...]]],
    parent_rows: list[BaseModel],
) -> None:
    """Fold each referenced parent row's attributes into per-row LLM context.

    For every child row, looks up the parent row its foreign key points at and
    records that parent's attributes (minus the parent's own primary key) under a
    readable key: a single ``*_id`` column becomes its stem (``customer_id`` ->
    ``customer``); otherwise the referenced model's name is used. Rows whose
    foreign key is ``None`` are skipped.
    """
    if not parent_rows:
        return
    parent_pk_names = _primary_key_names(fk.target)
    parent_by_pk = dict(zip(pk_pools[fk.target], parent_rows, strict=True))

    if len(fk.columns) == 1 and fk.columns[0].endswith("_id"):
        key = fk.columns[0][:-3]
    elif len(fk.columns) == 1:
        key = fk.columns[0]
    else:
        name = fk.target.__name__
        key = name[0].lower() + name[1:]

    ref_by_parent = dict(zip(fk.columns, fk.ref_columns, strict=True))
    for row, ctx in zip(prefilled, relational_context, strict=True):
        values = {ref_by_parent[col]: row.get(col) for col in fk.columns}
        if any(v is None for v in values.values()):
            continue
        parent_tuple = tuple(values[name] for name in parent_pk_names)
        parent = parent_by_pk.get(parent_tuple)
        if parent is None:
            continue
        ctx[key] = {
            name: value
            for name, value in parent.model_dump().items()
            if name not in parent_pk_names
        }


async def generate_dataset(
    counts: dict[type[BaseModel], int],
    *,
    seed: int | None = None,
    context: str = "general",
) -> Dataset:
    """Generate several related models together with referential integrity.

    Models are generated parent-first (topologically sorted by their foreign-key
    dependencies). Primary keys are unique; each foreign key is assigned a real
    primary-key value from the referenced model.

    Args:
        counts: Mapping of model class to the number of rows to generate.
        seed: Optional seed for reproducible primary/foreign keys and sampling.
        context: Optional generation context passed to each model.

    Returns:
        A :class:`Dataset` mapping each model class to its generated rows.
    """
    # Imported here to avoid a circular import at module load time.
    from .generator import _generate_with_distribution_sampling

    order = _resolve_generation_order(list(counts))
    by_name = {m.__name__: m for m in counts}
    key_rng = np.random.default_rng(seed)

    pk_pools: dict[type[BaseModel], list[tuple[Any, ...]]] = {}
    tables: dict[type[BaseModel], list[BaseModel]] = {}

    for idx, model in enumerate(order):
        pk_cols = _primary_key_columns(model)
        resolved_fks = _resolve_foreign_keys(model, by_name)

        prefilled, pk_pool, relational_context, count = _generate_keys(
            model,
            counts[model],
            pk_cols,
            resolved_fks,
            pk_pools,
            tables,
            key_rng,
        )
        if pk_pool is not None:
            pk_pools[model] = pk_pool

        model_seed = None if seed is None else seed + idx + 1
        tables[model] = await _generate_with_distribution_sampling(
            model,
            count,
            context,
            model_seed,
            prefilled=prefilled,
            relational_context=relational_context,
        )

    return Dataset(tables)


def generate_dataset_sync(
    counts: dict[type[BaseModel], int],
    *,
    seed: int | None = None,
    context: str = "general",
) -> Dataset:
    """Synchronous wrapper around :func:`generate_dataset`."""
    from .generator import _run_coro

    return _run_coro(generate_dataset(counts, seed=seed, context=context))
