"""Relational (multi-model) synthetic data generation.

Adds primary/foreign-key field specs and a ``generate_dataset`` orchestrator so
several related Pydantic models can be generated together with referential
integrity: primary keys are unique, and every foreign key points at a real
primary key of the referenced model.

Example:
    from typing import Annotated
    from pydantic import BaseModel
    from gendantic import PrimaryKey, ForeignKey, Normal, generate_dataset

    class Customer(BaseModel):
        id: Annotated[int, PrimaryKey()]
        name: str

    class Order(BaseModel):
        id: Annotated[int, PrimaryKey()]
        customer_id: Annotated[int, ForeignKey(Customer)]
        amount: Annotated[float, Normal(mean=200, std=80)]

    dataset = await generate_dataset({Customer: 100, Order: 500}, seed=42)
    customers = dataset[Customer]   # 100 rows, unique ids
    orders = dataset[Order]         # 500 rows, each customer_id in customers
"""

import uuid
from collections.abc import Iterator
from dataclasses import dataclass
from typing import TYPE_CHECKING, Annotated, Any, get_args, get_origin

import numpy as np
from pydantic import BaseModel

if TYPE_CHECKING:
    import pandas as pd


@dataclass(frozen=True)
class PrimaryKey:
    """Marks a field as the model's primary key.

    Values are generated by the engine (never asked of the LLM) and are unique
    within the generated rows.

    Args:
        strategy: How to generate key values.
            - ``"auto"`` (default): sequential integers for ``int`` fields,
              random UUID hex strings for ``str`` fields.
            - ``"sequential"``: integers ``1..count``.
            - ``"uuid"``: random UUID hex strings.
    """

    strategy: str = "auto"

    def generate(
        self, count: int, base_type: type, rng: np.random.Generator
    ) -> list[Any]:
        """Generate ``count`` unique primary-key values for the given field type."""
        strategy = self.strategy
        if strategy == "auto":
            strategy = "uuid" if base_type is str else "sequential"

        if strategy == "sequential":
            return list(range(1, count + 1))
        if strategy == "uuid":
            # Draw UUID bytes from the seeded rng so datasets are reproducible.
            return [uuid.UUID(bytes=rng.bytes(16)).hex for _ in range(count)]

        raise ValueError(
            f"Unknown PrimaryKey strategy {strategy!r}; "
            "expected 'auto', 'sequential', or 'uuid'."
        )


@dataclass(frozen=True)
class ForeignKey:
    """Marks a field as a reference to another model's primary key.

    The engine assigns each row a primary-key value drawn uniformly at random
    from the referenced model's generated rows, guaranteeing referential
    integrity.

    Args:
        model: The referenced Pydantic model class (must also be generated), or
            its class name as a string. Use a string forward reference for
            self-references or mutual references, where the class isn't yet
            defined in its own body — e.g. ``ForeignKey("Employee")`` for a
            ``manager_id`` on ``Employee``.
        field: Name of the referenced primary-key field. Defaults to the
            referenced model's ``PrimaryKey`` field.
        nullable: If True, some values are left as ``None``.
        null_probability: Fraction of values set to ``None`` when ``nullable``.
    """

    model: type[BaseModel] | str
    field: str | None = None
    nullable: bool = False
    null_probability: float = 0.1


class Dataset:
    """A generated collection of related tables, keyed by model class.

    Behaves like a read-only mapping: ``dataset[Customer]`` returns the list of
    generated ``Customer`` instances.
    """

    def __init__(self, tables: dict[type[BaseModel], list[BaseModel]]):
        self._tables = tables

    def __getitem__(self, model: type[BaseModel]) -> list[BaseModel]:
        return self._tables[model]

    def __iter__(self) -> Iterator[type[BaseModel]]:
        return iter(self._tables)

    def __len__(self) -> int:
        return len(self._tables)

    def __contains__(self, model: object) -> bool:
        return model in self._tables

    def items(self) -> Iterator[tuple[type[BaseModel], list[BaseModel]]]:
        return iter(self._tables.items())

    def to_dataframes(self) -> dict[str, "pd.DataFrame"]:
        """Convert every table to a pandas DataFrame, keyed by model name."""
        from .export import to_dataframe

        return {
            model.__name__: to_dataframe(records)
            for model, records in self._tables.items()
        }


def extract_primary_key(
    model_class: type[BaseModel],
) -> tuple[str, PrimaryKey, type] | None:
    """Return ``(field_name, PrimaryKey, base_type)`` for the model's PK, if any."""
    annotations = getattr(model_class, "__annotations__", {})
    for field_name, annotation in annotations.items():
        if get_origin(annotation) is Annotated:
            args = get_args(annotation)
            base_type = args[0]
            for arg in args[1:]:
                if isinstance(arg, PrimaryKey):
                    return field_name, arg, base_type
    return None


def extract_foreign_keys(model_class: type[BaseModel]) -> dict[str, ForeignKey]:
    """Return a mapping of ``field_name -> ForeignKey`` for the model."""
    foreign_keys: dict[str, ForeignKey] = {}
    annotations = getattr(model_class, "__annotations__", {})
    for field_name, annotation in annotations.items():
        if get_origin(annotation) is Annotated:
            args = get_args(annotation)
            for arg in args[1:]:
                if isinstance(arg, ForeignKey):
                    foreign_keys[field_name] = arg
                    break
    return foreign_keys


def _resolve_fk_model(
    fk: ForeignKey,
    referrer: type[BaseModel],
    fk_field: str,
    by_name: dict[str, type[BaseModel]],
) -> type[BaseModel]:
    """Resolve a foreign key's target to a model class in the dataset.

    Accepts either a class or a string forward reference (the target's class
    name). Raises ValueError if the target isn't part of the dataset.
    """
    target = fk.model
    if isinstance(target, str):
        resolved = by_name.get(target)
        if resolved is None:
            raise ValueError(
                f"{referrer.__name__}.{fk_field} references {target!r}, "
                f"which is not included in the dataset. Add it with a count."
            )
        return resolved
    if target not in by_name.values():
        raise ValueError(
            f"{referrer.__name__}.{fk_field} references {target.__name__}, "
            f"which is not included in the dataset. Add it with a count."
        )
    return target


def _resolve_generation_order(
    models: list[type[BaseModel]],
) -> list[type[BaseModel]]:
    """Topologically sort models so referenced (parent) models come first.

    Raises ValueError on a cyclic foreign-key dependency, or if a foreign key
    references a model that is not being generated.
    """
    by_name = {m.__name__: m for m in models}
    # edges: parent -> {children}; in_degree counts unresolved parents per model
    dependencies: dict[type[BaseModel], set[type[BaseModel]]] = {
        m: set() for m in models
    }
    for model in models:
        for fk_field, fk in extract_foreign_keys(model).items():
            target = _resolve_fk_model(fk, model, fk_field, by_name)
            if target is not model:
                dependencies[model].add(target)

    order: list[type[BaseModel]] = []
    resolved: set[type[BaseModel]] = set()
    while len(order) < len(models):
        progressed = False
        for model in models:
            if model in resolved:
                continue
            if dependencies[model] <= resolved:
                order.append(model)
                resolved.add(model)
                progressed = True
        if not progressed:
            remaining = [m.__name__ for m in models if m not in resolved]
            raise ValueError(
                f"Cyclic foreign-key dependency among models: {', '.join(remaining)}"
            )
    return order


def _assign_foreign_keys(
    prefilled: list[dict[str, Any]],
    fk_field: str,
    fk: ForeignKey,
    parent_pool: list[Any],
    rng: np.random.Generator,
) -> None:
    """Assign each row a foreign-key value drawn uniformly from ``parent_pool``."""
    for row in prefilled:
        if fk.nullable and rng.random() < fk.null_probability:
            row[fk_field] = None
        else:
            row[fk_field] = parent_pool[int(rng.integers(len(parent_pool)))]


def _attach_relational_context(
    relational_context: list[dict[str, Any]],
    prefilled: list[dict[str, Any]],
    fk_field: str,
    parent_pk_field: str,
    parent_pk_pool: list[Any],
    parent_rows: list[BaseModel],
) -> None:
    """Fold each referenced parent row's attributes into per-row LLM context.

    For every child row, looks up the parent row its foreign key points at and
    records that parent's attributes (minus the parent's own primary key) under
    a readable key (the foreign-key field name without a trailing ``_id``). This
    lets the LLM generate text coherent with the actual related row rather than
    an opaque key value. Skipped for ``None`` foreign keys.
    """
    if not parent_rows:
        return
    parent_by_pk = dict(zip(parent_pk_pool, parent_rows, strict=True))
    key = fk_field[:-3] if fk_field.endswith("_id") else fk_field
    for row, ctx in zip(prefilled, relational_context, strict=True):
        fk_value = row.get(fk_field)
        if fk_value is None:
            continue
        parent = parent_by_pk.get(fk_value)
        if parent is None:
            continue
        attributes = {
            name: value
            for name, value in parent.model_dump().items()
            if name != parent_pk_field
        }
        ctx[key] = attributes


async def generate_dataset(
    counts: dict[type[BaseModel], int],
    *,
    seed: int | None = None,
    context: str = "general",
) -> Dataset:
    """Generate several related models together with referential integrity.

    Models are generated parent-first (topologically sorted by their foreign-key
    dependencies). Primary keys are unique; each foreign key is assigned a real
    primary-key value from the referenced model.

    Args:
        counts: Mapping of model class to the number of rows to generate.
        seed: Optional seed for reproducible primary/foreign keys and sampling.
        context: Optional generation context passed to each model.

    Returns:
        A :class:`Dataset` mapping each model class to its generated rows.
    """
    # Imported here to avoid a circular import at module load time.
    from .generator import _generate_with_distribution_sampling

    order = _resolve_generation_order(list(counts))
    by_name = {m.__name__: m for m in counts}
    key_rng = np.random.default_rng(seed)

    pk_pools: dict[type[BaseModel], list[Any]] = {}
    tables: dict[type[BaseModel], list[BaseModel]] = {}

    for idx, model in enumerate(order):
        count = counts[model]
        prefilled: list[dict[str, Any]] = [{} for _ in range(count)]
        relational_context: list[dict[str, Any]] = [{} for _ in range(count)]

        # Primary key: generate unique values and record the pool for children.
        pk_info = extract_primary_key(model)
        if pk_info is not None:
            pk_field, pk_spec, pk_type = pk_info
            pk_values = pk_spec.generate(count, pk_type, key_rng)
            for row, value in zip(prefilled, pk_values, strict=True):
                row[pk_field] = value
            pk_pools[model] = pk_values

        # Foreign keys: draw from the referenced model's primary-key pool.
        for fk_field, fk in extract_foreign_keys(model).items():
            target = _resolve_fk_model(fk, model, fk_field, by_name)
            parent_pk = extract_primary_key(target)
            if parent_pk is None:
                raise ValueError(
                    f"{model.__name__}.{fk_field} references {target.__name__}, "
                    f"which has no PrimaryKey field."
                )
            if fk.field is not None and fk.field != parent_pk[0]:
                raise ValueError(
                    f"{model.__name__}.{fk_field} references "
                    f"{target.__name__}.{fk.field}, but foreign keys must "
                    f"reference the primary key ({target.__name__}.{parent_pk[0]})."
                )
            _assign_foreign_keys(prefilled, fk_field, fk, pk_pools[target], key_rng)
            _attach_relational_context(
                relational_context,
                prefilled,
                fk_field,
                parent_pk[0],
                pk_pools.get(target, []),
                tables.get(target, []),
            )

        model_seed = None if seed is None else seed + idx + 1
        tables[model] = await _generate_with_distribution_sampling(
            model,
            count,
            context,
            model_seed,
            prefilled=prefilled,
            relational_context=relational_context,
        )

    return Dataset(tables)


def generate_dataset_sync(
    counts: dict[type[BaseModel], int],
    *,
    seed: int | None = None,
    context: str = "general",
) -> Dataset:
    """Synchronous wrapper around :func:`generate_dataset`."""
    from .generator import _run_coro

    return _run_coro(generate_dataset(counts, seed=seed, context=context))
