"""Single-model (non-relational) generation with an LLM.

Two demos on one Pydantic model each:

1. ``demo_simple`` - the smallest useful case: a couple of plain text fields the
   LLM fills in from a business context. No statistics, no relations.
2. ``demo_distributions_and_copulas`` - the statistical side: numeric fields are
   sampled from distributions, correlated via a copula, and only the semantic
   field is generated by the LLM. The generated correlation is checked against
   the target so you can see the copula working.

Needs a LiteLLM proxy. Configure it with the standard environment variables
before running:

    export LITELLM_API_BASE="https://your-litellm-proxy/v1"
    export LITELLM_API_KEY="your-proxy-key"        # if the proxy requires auth
    export LITELLM_MODEL="openai/gpt-4o-mini"       # openai/ prefix routes the
                                                    # SDK at an OpenAI-compatible
                                                    # proxy endpoint

Run it with:

    uv run python examples/llm_single_model.py
"""

import os
import statistics
import sys
from typing import Annotated

from pydantic import BaseModel, Field

from gendantic import (
    Beta,
    Correlations,
    Normal,
    Uniform,
    generate_synthetic_data_sync,
)


class SupportTicket(BaseModel):
    """A customer support ticket."""

    subject: str  # LLM-generated, short summary line
    description: str  # LLM-generated, a sentence or two


class Employee(BaseModel):
    """An employee record with correlated numeric fields."""

    # Numeric fields sampled by numpy...
    age: Annotated[int, Uniform(min=22, max=65)]
    years_experience: Annotated[int, Uniform(min=0, max=40)]
    salary: Annotated[float, Normal(mean=70000, std=18000)] = Field(ge=25000)
    performance: Annotated[float, Beta(alpha=5, beta=2)]
    # ...and one semantic field generated by the LLM.
    job_title: str

    # Copula-based correlations between the sampled fields.
    __correlations__ = Correlations(
        ("age", "years_experience", 0.85),  # older -> more experience
        ("years_experience", "salary", 0.6),  # experience -> higher salary
        ("performance", "salary", 0.5, "gumbel"),  # top performers paid more
    )


def demo_simple() -> None:
    print("=== Simple: LLM fills in text fields ===")
    tickets = generate_synthetic_data_sync(
        SupportTicket,
        count=5,
        context="A UK broadband provider's technical support queue",
        seed=1,
    )
    for t in tickets:
        print(f"  [{t.subject}] {t.description}")
    print()


def demo_distributions_and_copulas() -> None:
    print("=== Distributions + copulas: stats sampled, correlations preserved ===")
    count = 300
    employees = generate_synthetic_data_sync(Employee, count=count, seed=42)

    ages = [e.age for e in employees]
    experience = [e.years_experience for e in employees]
    salaries = [e.salary for e in employees]

    age_exp = statistics.correlation(ages, experience)
    exp_salary = statistics.correlation(experience, salaries)
    print(f"  age <-> years_experience: {age_exp:+.2f} (target +0.85)")
    print(f"  years_experience <-> salary: {exp_salary:+.2f} (target +0.60)")
    print("\n  Sample rows:")
    for e in employees[:5]:
        print(
            f"    {e.job_title:<28} age={e.age} exp={e.years_experience}y "
            f"£{e.salary:,.0f} perf={e.performance:.2f}"
        )
    print()


def main() -> None:
    if not os.environ.get("LITELLM_API_BASE"):
        sys.exit(
            "No LiteLLM proxy configured. Set LITELLM_API_BASE (and, if needed, "
            "LITELLM_API_KEY / LITELLM_MODEL) before running this example."
        )
    print(
        f"Using proxy {os.environ['LITELLM_API_BASE']} "
        f"model {os.environ.get('LITELLM_MODEL', '(default)')}\n"
    )
    demo_simple()
    demo_distributions_and_copulas()


if __name__ == "__main__":
    main()
